### ISSUE TITLE
[Update or add citation]: 

### ISSUE THREAD

**Issue by CROWE-BRI** [RWSCollab/science-plan#2]
### Contact Details

kate.williams@briwildlife.org

### In what section is the outdated or missing citation?

Section 10.1 - Advisian/BRI project "Technology needs for scientifically robust wildlife monitoring and adaptive management"

### Provide us with the new or updated citation.

All project files are publicly available at: https://nationaloffshorewind.org/projects/technology-development-priorities-for-scientifically-robust-and-operationally-compatible-wildlife-monitoring-and-adaptive-management/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eshumchenia** [comment]
Thanks Kate! This was updated as described in https://github.com/RWSCollab/science-plan/commit/843cf5a0becfeb220e3df21317785714881a2838

Here's a quick link to the revised text: https://rwscollab.github.io/science-plan/technology.html#introduction
